package com.cybertek.tests.day5;

public class F_Windows_Tabs_information_Syntax {

    //-> WINDOWS
    //-> For selenium there is no difference in between a window and a tab.
    //-> It treats both of them as just a window.

    //-HOW DO WE HANDLE WINDOWS USING SELENIUM?
    //-> We use something called WINDOW HANDLE to handle windows in selenium.

    //-What is a window handle and where does it come from?
    //-> A window handle is uniqueID that is automatically and randomly generated by selenium for each window selenium opens.
    //-> A window handle is alphanumerical, and unique to each window
    //-> And selenium uses window handles to identify and switch to using window handles.

    //-How do we switch to a different window using selenium?
                    //driver.switchTo().window(WINDOWHANDLE);

    //-How do we get the handle of the current window?
                        //driver..getWindowHandle(); ->Returns String
    //- .getWindowHandle();
    //- This method returns us the current window handle as String
              //String currentHandle = driver.getWindowHandle();

    //How to get all of the handles of currently opened window?
    //
    //- driver.getWindowHandles();  ->Returns All Window handles as a SET of String
    //- This method returns all of the currently opened windows handles.
    //- What is the return type of this method?
    //- Return type of this method is a Set of Strings.
    //Set<String>
    //-How do we create the logic to switch to another window?
    //- We create a for-each loop to loop through the Set of Strings that is returned by .getWindowHandles(); method.
    //- Then we use driver.switchTo().window(PASS HANDLE HERE);


    //READ ABOVE!!!!
    //BUT BELOW IS A BASIC SUMMARIZING IT!!!


    //----------------------------------------------------------------------------------------//
    //Important Syntax
    // driver.getWindowHandle() ->returns String-> We store a single Window in it!
    //driver.getWindowHandles() ->returns Set<String> -> We store multiple Windows in it!
    //We use Foreach loop to switch windows!!
    //driver.switchTo().window(WINDOWHANDLE); ->to Switch
    //WINDOWHANDLE-> item, each OR a specific window that you store before
    // by using String window = driver.getWindowHandle()...
    //-----------------------------------------------------------------------------------------//



}
